/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: JdQiVgRuu/3bDE6yVyi92Uv0r0WujeCvHxy2ebwVIFHkp5gG46SsixjmW04EYXNMAVvQXRjBZL6MlUzJAfqxrA==
 */

/* eslint-disable */
// tslint:disable

interface Address {
  city: string
  country: string
  houseNumber: (string) | null
  id: string & {readonly __brand?: 'address_id'}
  street: string
  zipCode: string
}
export default Address;

interface Address_InsertParameters {
  city: string
  country: string
  houseNumber?: (string) | null
  id: string & {readonly __brand?: 'address_id'}
  street: string
  zipCode: string
}
export type {Address_InsertParameters}
