/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Xj9IXa3cfuMsg+XlOXIitKj1SJFUiK7DWaVRuTbAH5NU1pX4XDPqWyFOSA9LVRtlLkvpxVvL+tWzfia6LXYNjw==
 */

/* eslint-disable */
// tslint:disable

import Address, {Address_InsertParameters} from './address'

interface DatabaseSchema {
  address: {record: Address, insert: Address_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  Address,
  Address_InsertParameters,
}
